/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/zshi-redhat/network-device-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetDevicePools implements NetDevicePoolInterface
type FakeNetDevicePools struct {
	Fake *FakeNetdevV1alpha1
	ns   string
}

var netdevicepoolsResource = schema.GroupVersionResource{Group: "netdev", Version: "v1alpha1", Resource: "netdevicepools"}

var netdevicepoolsKind = schema.GroupVersionKind{Group: "netdev", Version: "v1alpha1", Kind: "NetDevicePool"}

// Get takes name of the netDevicePool, and returns the corresponding netDevicePool object, and an error if there is any.
func (c *FakeNetDevicePools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetDevicePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(netdevicepoolsResource, c.ns, name), &v1alpha1.NetDevicePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePool), err
}

// List takes label and field selectors, and returns the list of NetDevicePools that match those selectors.
func (c *FakeNetDevicePools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetDevicePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(netdevicepoolsResource, netdevicepoolsKind, c.ns, opts), &v1alpha1.NetDevicePoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetDevicePoolList{ListMeta: obj.(*v1alpha1.NetDevicePoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetDevicePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netDevicePools.
func (c *FakeNetDevicePools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(netdevicepoolsResource, c.ns, opts))

}

// Create takes the representation of a netDevicePool and creates it.  Returns the server's representation of the netDevicePool, and an error, if there is any.
func (c *FakeNetDevicePools) Create(ctx context.Context, netDevicePool *v1alpha1.NetDevicePool, opts v1.CreateOptions) (result *v1alpha1.NetDevicePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(netdevicepoolsResource, c.ns, netDevicePool), &v1alpha1.NetDevicePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePool), err
}

// Update takes the representation of a netDevicePool and updates it. Returns the server's representation of the netDevicePool, and an error, if there is any.
func (c *FakeNetDevicePools) Update(ctx context.Context, netDevicePool *v1alpha1.NetDevicePool, opts v1.UpdateOptions) (result *v1alpha1.NetDevicePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(netdevicepoolsResource, c.ns, netDevicePool), &v1alpha1.NetDevicePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetDevicePools) UpdateStatus(ctx context.Context, netDevicePool *v1alpha1.NetDevicePool, opts v1.UpdateOptions) (*v1alpha1.NetDevicePool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(netdevicepoolsResource, "status", c.ns, netDevicePool), &v1alpha1.NetDevicePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePool), err
}

// Delete takes name of the netDevicePool and deletes it. Returns an error if one occurs.
func (c *FakeNetDevicePools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(netdevicepoolsResource, c.ns, name), &v1alpha1.NetDevicePool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetDevicePools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(netdevicepoolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetDevicePoolList{})
	return err
}

// Patch applies the patch and returns the patched netDevicePool.
func (c *FakeNetDevicePools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetDevicePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(netdevicepoolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetDevicePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePool), err
}
