/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/zshi-redhat/network-device-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetDevicePoolLists implements NetDevicePoolListInterface
type FakeNetDevicePoolLists struct {
	Fake *FakeNetdevV1alpha1
	ns   string
}

var netdevicepoollistsResource = schema.GroupVersionResource{Group: "netdev", Version: "v1alpha1", Resource: "netdevicepoollists"}

var netdevicepoollistsKind = schema.GroupVersionKind{Group: "netdev", Version: "v1alpha1", Kind: "NetDevicePoolList"}

// Get takes name of the netDevicePoolList, and returns the corresponding netDevicePoolList object, and an error if there is any.
func (c *FakeNetDevicePoolLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetDevicePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(netdevicepoollistsResource, c.ns, name), &v1alpha1.NetDevicePoolList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePoolList), err
}

// List takes label and field selectors, and returns the list of NetDevicePoolLists that match those selectors.
func (c *FakeNetDevicePoolLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetDevicePoolListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(netdevicepoollistsResource, netdevicepoollistsKind, c.ns, opts), &v1alpha1.NetDevicePoolListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePoolListList), err
}

// Watch returns a watch.Interface that watches the requested netDevicePoolLists.
func (c *FakeNetDevicePoolLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(netdevicepoollistsResource, c.ns, opts))

}

// Create takes the representation of a netDevicePoolList and creates it.  Returns the server's representation of the netDevicePoolList, and an error, if there is any.
func (c *FakeNetDevicePoolLists) Create(ctx context.Context, netDevicePoolList *v1alpha1.NetDevicePoolList, opts v1.CreateOptions) (result *v1alpha1.NetDevicePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(netdevicepoollistsResource, c.ns, netDevicePoolList), &v1alpha1.NetDevicePoolList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePoolList), err
}

// Update takes the representation of a netDevicePoolList and updates it. Returns the server's representation of the netDevicePoolList, and an error, if there is any.
func (c *FakeNetDevicePoolLists) Update(ctx context.Context, netDevicePoolList *v1alpha1.NetDevicePoolList, opts v1.UpdateOptions) (result *v1alpha1.NetDevicePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(netdevicepoollistsResource, c.ns, netDevicePoolList), &v1alpha1.NetDevicePoolList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePoolList), err
}

// Delete takes name of the netDevicePoolList and deletes it. Returns an error if one occurs.
func (c *FakeNetDevicePoolLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(netdevicepoollistsResource, c.ns, name), &v1alpha1.NetDevicePoolList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetDevicePoolLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(netdevicepoollistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetDevicePoolListList{})
	return err
}

// Patch applies the patch and returns the patched netDevicePoolList.
func (c *FakeNetDevicePoolLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetDevicePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(netdevicepoollistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetDevicePoolList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetDevicePoolList), err
}
