# permissions for end users to view netdevicepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdevicepool-viewer-role
rules:
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevicepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevicepools/status
  verbs:
  - get
