# permissions for end users to edit netdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdevice-editor-role
rules:
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevices/status
  verbs:
  - get
