
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevicepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevicepools/finalizers
  verbs:
  - update
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevicepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevices/finalizers
  verbs:
  - update
- apiGroups:
  - netdev.k8s.cncf.io
  resources:
  - netdevices/status
  verbs:
  - get
  - patch
  - update
