/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	netdevv1alpha1 "github.com/zshi-redhat/network-device-operator/api/v1alpha1"
	versioned "github.com/zshi-redhat/network-device-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/zshi-redhat/network-device-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/zshi-redhat/network-device-operator/pkg/client/listers/netdev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetDevicePoolInformer provides access to a shared informer and lister for
// NetDevicePools.
type NetDevicePoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetDevicePoolLister
}

type netDevicePoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetDevicePoolInformer constructs a new informer for NetDevicePool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetDevicePoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetDevicePoolInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetDevicePoolInformer constructs a new informer for NetDevicePool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetDevicePoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetdevV1alpha1().NetDevicePools(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetdevV1alpha1().NetDevicePools(namespace).Watch(context.TODO(), options)
			},
		},
		&netdevv1alpha1.NetDevicePool{},
		resyncPeriod,
		indexers,
	)
}

func (f *netDevicePoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetDevicePoolInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *netDevicePoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&netdevv1alpha1.NetDevicePool{}, f.defaultInformer)
}

func (f *netDevicePoolInformer) Lister() v1alpha1.NetDevicePoolLister {
	return v1alpha1.NewNetDevicePoolLister(f.Informer().GetIndexer())
}
