---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-device-plugin
  namespace: {{.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-device-plugin
  namespace: {{.Namespace}}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-device-plugin
  namespace: {{.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-device-plugin
subjects:
  - kind: ServiceAccount
    name: network-device-plugin
    namespace: {{.Namespace}}
