// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceFeature) DeepCopyInto(out *DeviceFeature) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceFeature.
func (in *DeviceFeature) DeepCopy() *DeviceFeature {
	if in == nil {
		return nil
	}
	out := new(DeviceFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceMode) DeepCopyInto(out *DeviceMode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMode.
func (in *DeviceMode) DeepCopy() *DeviceMode {
	if in == nil {
		return nil
	}
	out := new(DeviceMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSelector) DeepCopyInto(out *DeviceSelector) {
	*out = *in
	if in.Vendors != nil {
		in, out := &in.Vendors, &out.Vendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PciAddrs != nil {
		in, out := &in.PciAddrs, &out.PciAddrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSelector.
func (in *DeviceSelector) DeepCopy() *DeviceSelector {
	if in == nil {
		return nil
	}
	out := new(DeviceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDevice) DeepCopyInto(out *NetDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDevice.
func (in *NetDevice) DeepCopy() *NetDevice {
	if in == nil {
		return nil
	}
	out := new(NetDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceConfig) DeepCopyInto(out *NetDeviceConfig) {
	*out = *in
	out.Mode = in.Mode
	in.Feature.DeepCopyInto(&out.Feature)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceConfig.
func (in *NetDeviceConfig) DeepCopy() *NetDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(NetDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceFeature) DeepCopyInto(out *NetDeviceFeature) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceFeature.
func (in *NetDeviceFeature) DeepCopy() *NetDeviceFeature {
	if in == nil {
		return nil
	}
	out := new(NetDeviceFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceList) DeepCopyInto(out *NetDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceList.
func (in *NetDeviceList) DeepCopy() *NetDeviceList {
	if in == nil {
		return nil
	}
	out := new(NetDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDevicePool) DeepCopyInto(out *NetDevicePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDevicePool.
func (in *NetDevicePool) DeepCopy() *NetDevicePool {
	if in == nil {
		return nil
	}
	out := new(NetDevicePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetDevicePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDevicePoolList) DeepCopyInto(out *NetDevicePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetDevicePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDevicePoolList.
func (in *NetDevicePoolList) DeepCopy() *NetDevicePoolList {
	if in == nil {
		return nil
	}
	out := new(NetDevicePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetDevicePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDevicePoolSpec) DeepCopyInto(out *NetDevicePoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.DeviceSelector.DeepCopyInto(&out.DeviceSelector)
	in.Device.DeepCopyInto(&out.Device)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDevicePoolSpec.
func (in *NetDevicePoolSpec) DeepCopy() *NetDevicePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetDevicePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDevicePoolStatus) DeepCopyInto(out *NetDevicePoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDevicePoolStatus.
func (in *NetDevicePoolStatus) DeepCopy() *NetDevicePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetDevicePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceSpec) DeepCopyInto(out *NetDeviceSpec) {
	*out = *in
	out.DeviceType = in.DeviceType
	in.DeviceFeature.DeepCopyInto(&out.DeviceFeature)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceSpec.
func (in *NetDeviceSpec) DeepCopy() *NetDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(NetDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceStatus) DeepCopyInto(out *NetDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceStatus.
func (in *NetDeviceStatus) DeepCopy() *NetDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(NetDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDeviceType) DeepCopyInto(out *NetDeviceType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDeviceType.
func (in *NetDeviceType) DeepCopy() *NetDeviceType {
	if in == nil {
		return nil
	}
	out := new(NetDeviceType)
	in.DeepCopyInto(out)
	return out
}
